### ISSUE TITLE
Bump clj-gatling version to 0.8.5

### ISSUE THREAD

**Issue by greywolve** [mhjort/clojider#7]
Hey @mhjort , thanks for merging my PR on the clj-gatling side, would you mind bumping the version here, and releasing a new Clojider too when you get a chance? We'd really like to use the new scenario specific context in our tests. Thanks! :)

**Comment by mhjort** [comment]
No problem. Just released Clojider ```0.4.3``` with latest clj-gatling.

**Comment by greywolve** [comment]
Thanks so much. :)
